name: article-tdem

channels:
  - conda-forge
  - defaults
dependencies:
  - "libblas=*=*mkl"
  - emg3d<0.17.0
  - discretize<=0.6.2
  - empymod>=2.0.0
  - simpeg
  - matplotlib
  - jupyter
  - pymatsolver
  - scooby
  - ipykernel
  - h5py
  - mkl-service
