name: article-tdem

channels:
  - conda-forge
  - defaults
dependencies:
  - "libblas=*=*mkl"
  - emg3d
  - empymod
  - simpeg
  - matplotlib
  - jupyter
  - pymatsolver
  - scooby
  - ipykernel
  - h5py
  - mkl-service
